[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 12

[window]
opacity = 0.2 
dynamic_padding = true
padding = { x = 8, y = 8 }

[colors.primary]
background = "#0c0c0c"
foreground = "#d9d9d9" 

[colors.cursor]
cursor = "#7f2a2a"
text = "#1a1a1a"

[colors.selection]
background = "#333333"
text = "CellForeground"

[colors.normal]
black   = "#3f3f3f"
red     = "#af4f4f"
green   = "#6f8f6f"
yellow  = "#afaf6f"
blue    = "#6f6faf"
magenta = "#af6faf"
cyan    = "#6fafaf"
white   = "#ffffff"

[colors.bright]
black   = "#3f3f3f"
red     = "#af4f4f"
green   = "#6f8f6f"
yellow  = "#afaf6f"
blue    = "#6f6faf"
magenta = "#af6faf"
cyan    = "#6fafaf"
white   = "#ffffff"

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[scrolling]
history = 10000
multiplier = 3

# dull colours 
# black   = "#2b2b2b"
# red     = "#7f2a2a"
# green   = "#547754ff"
# yellow  = "#7f7f4f"
# blue    = "#4f4f7f"
# magenta = "#7f4f7f"
# cyan    = "#569e9e"
# white   = "#d9d9d9"